const express = require('express');
const router = express.Router();
const authRouter = require('./authroutes');
const adminRouter = require('./adminroutes');
const userRouter = require('./userroutes');
const SupportRouter = require('./supportroute');
const Languageroutes = require('./languageroutes');
const Settingsroute = require('./settingsroute');
const Reportroutes = require('./reportroutes');
const Dashboardroutes = require('./dashboardroutes');
const Commanroutes = require('./commanroutes');
const visaroutes = require('./visa');
const oktbroutes = require('./oktb');
const agentroutes = require('./agentroutes');
const countryroutes = require('./country');
const third_partyroutes = require('./third_party');
const bookingroutes = require('./booking');
const walletroutes = require('./walletroutes');
const airlineroutes = require("./airlineroutes");

router.use('/auth', authRouter);
router.use('/admin', adminRouter);
router.use("/user", userRouter);
router.use("/support", SupportRouter);
router.use("/language", Languageroutes);
router.use("/setting", Settingsroute);
router.use("/report", Reportroutes);
router.use("/home", Dashboardroutes);
router.use("/visa", visaroutes);
router.use("/oktb", oktbroutes);
router.use("/comman", Commanroutes);
router.use("/agent", agentroutes);
router.use("/country", countryroutes);
router.use("/third_party", third_partyroutes);
router.use("/booking", bookingroutes);
router.use("/wallet", walletroutes);
router.use("/airline", airlineroutes);
router.use("/offline_ticket", require("./offline_ticket"));

module.exports = router;